version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: Clear.22
      MYSQL_DATABASE: db_desafio
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: