version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5172:5172"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: http://192.168.1.139:3000
    volumes:
      - ./frontend:/app
    command: npm run start

  db:
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: Clear.22
      MYSQL_DATABASE: db_desafio
    volumes:
      - db_data:/var/lib/mysql
  
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: "mysql://root:Clear.22@localhost:3306/db_desafio?schema=public"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
volumes:
  db_data: